### ISSUE TITLE
Title tag issue on header.php

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/lc-orao#13]
The page source shows two <title> tags.
https://www.evernote.com/l/Ajm0sTp4YRpO3ZsO0h8gC06W1PzNQ2CMKs8

the problem:

https://www.evernote.com/l/Ajn8ABsQAlNH4IjFrw0M_3m47R7Wgo-0mjg

**Comment by lumberman** [comment]
wp_head() had nothing to do with wp_title

Most likely it's broken code in the theme. What theme is it?

**Comment by ghost** [comment]
Done
