### ISSUE TITLE
Remove Dates From Josephine Comments

### ISSUE THREAD

**Issue by lumberman** [live-composer/lc-orao#8]
Hey guys,

Can I get a "remove dates" from Josephine please?! Right now I'm turning down the font size to zero

Also the responsive design of the comment form module is bad too

<img width="439" alt="e793d742-a66d-11e6-9ed9-673beaf50aa1" src="https://cloud.githubusercontent.com/assets/1384471/20242862/2a3ba9f0-a8fb-11e6-8683-3e029e7d57d0.png">

https://github.com/live-composer/live-composer-page-builder/issues/377

**Comment by ghost** [comment]
The Theme Josephine was delete
